[package]
name = "common"
version = "0.1.0"
edition = "2021"

[features]
default = []
user = ["aya"]

[dependencies]
aya = { version = ">=0.11", optional = true }
network-types = "0.0.4"

[lib]
path = "src/lib.rs"
